# Generated by Django 4.2.5 on 2023-09-14 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docstore', '0002_rename_chat_docchat'),
    ]

    operations = [
        migrations.AddField(
            model_name='docfile',
            name='category',
            field=models.ManyToManyField(to='docstore.doccategory'),
        ),
    ]
