# Generated by Django 4.2.5 on 2023-09-14 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docstore', '0003_docfile_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docfile',
            name='file',
            field=models.FileField(upload_to='files/'),
        ),
    ]
