# Generated by Django 4.2.5 on 2023-09-14 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docstore', '0004_alter_docfile_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='docchat',
            name='slug',
            field=models.CharField(default='default_slug', max_length=255, verbose_name='Внешний ключ'),
            preserve_default=False,
        ),
    ]
